<?php

/**
 * Tweet
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    quieroeldiscorolling
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Tweet extends BaseTweet
{
	static public function hydrateFromDecodedResponse($t)
	{
		$screenName = $t['user']['screen_name']?$t['user']['screen_name']:false;
		if($screenName)
		{
			$user = sfGuardUserTable::getInstance()->retrieveOrCreateGuardUserByTwitterUsername($screenName, $t['user']['profile_image_url']);
			if($user && count($user->Tweets) == 0)
			{
				$tweet = new Tweet();
				$tweet['twitter_guid']    = $t['id_str']?$t['id_str']:false;
				$tweet['user_id']         = $user->getId();
				$tweet['text']            = $t['text']?$t['text']:false;
							
				return $tweet;
			}
		}
		
		return null;
	}
	
	public function postSave($event)
	{
		//Active the user when save the tweet
		$user = $this->getUser();
		if($user->getIsActive() == false)
		{
			$user->setIsActive(true);
			$user->save();
		}
	}
}