# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html; charset=UTF-8

  metas:
    title:         "Selena Gomez - Stars Dance"
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:
    - animate.min.css
    - disco.css

  javascripts:     ~

  has_layout:     true
  layout:         layout
